### PR TITLE
First commit of time kernel

### PR DESCRIPTION
**Pull request by fasshauer**

### CODE REVIEW

**Comment by mikemccourt** [comment]
Greg, learning how to do Pull Requests I see.  Very good.

So, we can certainly push this into master if we want, no problem with that, especially because it doesn't touch any of our core stuff.  The reason I put this in a branch was mostly to get us using better practices for jointly iterating on code (since there may be others participating in this).

The idea, in principle, is to work in the branch until we're ready to put it into master.  So, if you've looked at the branch, and you're cool with it, then we can merge it in.  To give your approval, add yourself as a reviewer (top right, click the gear, search for yourself) and give your review of the code.  You can click on `Files Changed` above to add line-by-line comments to your PR review if you would like to.

I'm going to assume that you did this by accident while trying to change branches.  I'm also going to assume that you successfully got into the `time-stuff` branch.  Lemme know how I can be of help.

**Comment by mikemccourt** [comment]
Ooh, but I just realized that you can't review your own PR (since you actually created this PR).  If you'd like, I can close this one, and start one of my own so that you can review it.  Or I can simply add comments to this myself as an example of what to expect.  If you were just trying to learn about this.

Hope your first day of class went well!

**Comment by fasshauer** [comment]
Just close it! I was confused with Github again. What I really wanted to do is update my local copy of the repo (sync, I guess). But because I had some uncommitted changes it wouldn’t sync. After ignoring those changes it worked :).

               Sorry,

               Greg



Greg Fasshauer
Professor and Head
Department of Applied Mathematics & Statistics
Colorado School of Mines
Golden, CO 80401
Office: Chauvenet Hall 141 A
Phone: +1 (303) 273-3803
Email: fasshauer@mines.edu<mailto:fasshauer@mines.edu>
[cid:image001.png@01D1EC14.1722C230]

**Comment by fasshauer** [comment]
And the first day of classes went fine. I spent all day today preparing the second one ☺.



Greg Fasshauer
Professor and Head
Department of Applied Mathematics & Statistics
Colorado School of Mines
Golden, CO 80401
Office: Chauvenet Hall 141 A
Phone: +1 (303) 273-3803
Email: fasshauer@mines.edu<mailto:fasshauer@mines.edu>
[cid:image001.png@01D1EC14.1722C230]

**Comment by fasshauer** [comment]
I’m fine either way. For now we can keep the branch separate, I guess.

               Greg



Greg Fasshauer
Professor and Head
Department of Applied Mathematics & Statistics
Colorado School of Mines
Golden, CO 80401
Office: Chauvenet Hall 141 A
Phone: +1 (303) 273-3803
Email: fasshauer@mines.edu<mailto:fasshauer@mines.edu>
[cid:image001.png@01D1EC14.1722C230]

**Pull request closed without merging**
